'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

type AuditData={ok:boolean;state?:{state_id:string;state_version:number;state_hash:string;overall_status:string;generated_at:string;published_at:string};audit_events?:Array<{id:string;actor:string;action:string;created_at:string}>;evidence_graph?:{lineage_status:string;prov_mapping:{entities:number;activities:number;agents:number};nodes:Array<{node_id:string;node_type:string;entity_id:string;created_at:string}>;edges:Array<unknown>}};

export default function StatePage(){
 const [data,setData]=useState<AuditData|null>(null); const [error,setError]=useState('');
 useEffect(()=>{fetch('/api/audit/state/latest?tenant_id=tenant-demo&subject_ref=bridge-cycle-synthetic',{cache:'no-store'}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error??'Falha na leitura');return body}).then(setData).catch(reason=>setError(reason instanceof Error?reason.message:'Falha na leitura'))},[]);
 return <main className="min-h-dvh bg-black px-5 py-8 text-[#f5f5f7]"><div className="mx-auto max-w-[720px]"><Link href="/" className="text-sm font-bold text-[#8fb1ff]">‹ Voltar ao painel</Link><div className="mt-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#adb1c0]">Auditoria somente leitura</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em]">Estado 360</h1></div>{!data&&!error&&<p className="mt-8 rounded-[24px] bg-[#1d1d1f] p-5 text-[#b9bbc5]">Carregando evidências…</p>}{error&&<p role="alert" className="mt-8 rounded-[24px] bg-[#321e1e] p-5 text-[#ffb4ab]">Não foi possível carregar: {error}</p>}{data?.state&&<div className="mt-8 space-y-5"><section className="rounded-[28px] border border-white/10 bg-[#1d1d1f] p-6"><div className="flex items-center justify-between gap-3"><div><small className="text-[#9295a2]">Status publicado</small><h2 className="mt-2 text-2xl font-semibold">Versão {data.state.state_version}</h2></div><span className="rounded-full bg-[#0e452d] px-3 py-2 text-xs font-bold text-[#55eca0]">{data.state.overall_status}</span></div><dl className="mt-6 grid gap-3 text-xs sm:grid-cols-2"><Item label="Publicado" value={date(data.state.published_at)}/><Item label="Gerado" value={date(data.state.generated_at)}/><Item label="Estado" value={data.state.state_id}/><Item label="Hash" value={data.state.state_hash}/></dl></section><section className="rounded-[28px] bg-[#1d1d1f] p-6"><h2 className="text-xl font-semibold">Evidence Graph</h2><div className="mt-5 grid grid-cols-3 gap-3"><Metric label="Entidades" value={data.evidence_graph?.prov_mapping.entities??0}/><Metric label="Atividades" value={data.evidence_graph?.prov_mapping.activities??0}/><Metric label="Agentes" value={data.evidence_graph?.prov_mapping.agents??0}/></div><p className="mt-4 text-sm text-[#b9bbc5]">Linhagem: <b className={data.evidence_graph?.lineage_status==='COMPLETE'?'text-[#55eca0]':'text-[#ffd983]'}>{data.evidence_graph?.lineage_status??'—'}</b></p></section><section className="rounded-[28px] bg-[#1d1d1f] p-6"><h2 className="text-xl font-semibold">Trilha de auditoria</h2>{data.audit_events?.length?<div className="mt-4 space-y-3">{data.audit_events.map(event=><article key={event.id} className="rounded-[18px] bg-[#29292b] p-4"><b className="text-sm">{event.action}</b><p className="mt-1 text-xs text-[#aeb1bd]">{event.actor} · {date(event.created_at)}</p></article>)}</div>:<p className="mt-4 text-sm text-[#ffd983]">Nenhum evento material encontrado para este estado sintético.</p>}</section></div>}</div></main>;
}
function date(value:string){return new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});}
function Item({label,value}:{label:string;value:string}){return <div className="min-w-0 rounded-[16px] bg-[#29292b] p-3"><dt className="text-[#9295a2]">{label}</dt><dd className="mt-1 truncate font-bold" title={value}>{value}</dd></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-[16px] bg-[#29292b] p-3 text-center"><b className="text-2xl">{value}</b><span className="mt-1 block text-[10px] text-[#9295a2]">{label}</span></div>}
