'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

type Item = { id: string; indicator_key: string; indicator_name: string; knowledge_type: string; version: number; status: string; layout_signature: string; approved_at: number | null; revoked_at: number | null };

export default function KnowledgePage() {
  const [items, setItems] = useState<Item[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  const load = () => fetch('/api/pobj/knowledge', { cache: 'no-store' }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setItems(data.items ?? []); }).catch(() => setError('Não foi possível carregar o conhecimento homologado.'));
  useEffect(load, []);
  async function revoke(id: string) { setBusy(id); setError(''); const response = await fetch('/api/pobj/knowledge', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id, action: 'revoke' }) }); if (!response.ok) setError('Não foi possível revogar este item.'); await load(); setBusy(''); }
  return <main className="min-h-dvh bg-black text-[#f5f5f7]"><div className="mx-auto max-w-[520px] px-6 pb-16 pt-[max(28px,env(safe-area-inset-top))]"><Link href="/" className="text-sm text-[#8fb1ff]">‹ Voltar ao painel</Link><p className="mt-10 text-[11px] font-bold uppercase tracking-[.18em] text-[#adb1c0]">Aprendizado supervisionado</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em]">Conhecimento POBJ</h1><p className="mt-3 text-sm leading-6 text-[#b9bbc5]">Somente mapeamentos e regras que você homologou. Metas, realizados e valores mensais nunca são reaproveitados.</p>{error && <p className="mt-5 rounded-[18px] bg-[#3a2022] p-4 text-sm text-[#ffb4ab]">{error}</p>}<section className="mt-7 space-y-3">{items.length === 0 && <div className="rounded-[24px] bg-[#1d1d1f] p-5 text-sm text-[#b9bbc5]">Nenhum conhecimento homologado ainda. Na revisão de um POBJ, marque apenas os indicadores cujo mapeamento deseja reutilizar.</div>}{items.map((item) => <article key={item.id} className="rounded-[24px] border border-white/10 bg-[#1d1d1f] p-5"><div className="flex items-start justify-between gap-3"><div><small className="font-bold uppercase text-[#8fb1ff]">{item.knowledge_type.replace('_', ' ')}</small><h2 className="mt-1 text-lg font-semibold">{item.indicator_name}</h2><p className="mt-1 text-xs text-[#90939f]">{item.indicator_key} · versão {item.version}</p></div><span className={`rounded-full px-3 py-1 text-[10px] font-bold ${item.status === 'ACTIVE' ? 'bg-[#0e452d] text-[#55eca0]' : 'bg-[#31291a] text-[#ffd983]'}`}>{item.status}</span></div><p className="mt-4 break-all rounded-[14px] bg-[#29292b] p-3 text-[10px] text-[#aeb1bd]">Layout: {item.layout_signature}</p>{item.status === 'ACTIVE' && <button disabled={busy === item.id} onClick={() => revoke(item.id)} className="mt-4 h-11 w-full rounded-full bg-[#402126] text-xs font-bold text-[#ffb4ab] disabled:opacity-40">{busy === item.id ? 'Revogando…' : 'Revogar para usos futuros'}</button>}</article>)}</section></div></main>;
}
