'use client';
import Link from 'next/link';
import { useState } from 'react';

type Tab='inicio'|'pobj'|'carteira'|'chat'|'mais';
const tasks=[['Ativar novas contas','5 contas no ciclo inicial','+50 pts'],['Tratar clientes sem contato','3 clientes acima de 60 dias','Cuidado'],['Confirmar produção pendente','Cielo e limite rotativo','+30 pts']];
const clients=[['Empresa Horizonte','D60 · São Fidélis','Sem movimentação há 32 dias'],['Comercial Boa Vista','Madura · Cambuci','Oportunidade de centralização'],['Grupo Nova Serra','D30 · São Fidélis','Rating alterado; validar evidência']];

export default function Home(){
 const [tab,setTab]=useState<Tab>('inicio'); const [sheet,setSheet]=useState<string|null>(null); const [message,setMessage]=useState('');
 const title=tab==='chat'?'Conversas':tab;
 return <main className="min-h-dvh bg-black text-[#f5f5f7]"><div className="mx-auto min-h-dvh max-w-[520px] pb-32">
  <header className="sticky top-0 z-30 flex items-center justify-between bg-black/90 px-6 pb-5 pt-[max(24px,env(safe-area-inset-top))] backdrop-blur-xl"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#adb1c0]">Diretor 360</p><h1 className="mt-3 text-[34px] font-semibold capitalize tracking-[-.04em]">{title}</h1></div><button onClick={()=>setSheet('Notificações')} className="relative grid h-12 w-12 place-items-center rounded-full bg-[#1d1d1f] text-xl">♢<i className="absolute right-1 top-1 h-3 w-3 rounded-full bg-[#ffbb00] ring-2 ring-black"/></button></header>
  {tab==='inicio'&&<div className="space-y-8 px-6"><section className="flex items-end justify-between py-3"><div><p className="text-sm text-[#b8bac4]">Visão geral</p><h2 className="mt-1 text-[40px] font-semibold leading-[1.08] tracking-[-.04em]">Bom dia,<br/>Rafael</h2></div><button onClick={()=>setTab('chat')} className="grid h-[72px] w-[72px] place-items-center rounded-full border-2 border-[#568dff] bg-[#17191d] text-4xl">🤖</button></section><Score/><section><h3 className="mb-4 text-xl font-semibold">✓ O que fazer hoje</h3><div className="space-y-3">{tasks.map((t,i)=><button key={t[0]} onClick={()=>setSheet(t[0])} className="flex w-full items-center gap-4 rounded-[28px] bg-[#1d1d1f] p-4 text-left"><span className="grid h-14 w-14 place-items-center rounded-[20px] bg-[#29364e] text-2xl text-[#b0c6ff]">{['↗','◈','⇄'][i]}</span><span className="min-w-0 flex-1"><b className="block truncate">{t[0]}</b><small className="mt-1 block truncate text-sm text-[#b9bbc5]">{t[1]}</small></span><em className="rounded-full bg-[#0e452d] px-3 py-2 text-xs font-bold not-italic text-[#55eca0]">{t[2]}</em></button>)}</div></section><Link href="/reviews" className="flex justify-between rounded-[28px] bg-[#281e1d] p-5"><div><small className="font-bold uppercase tracking-wider text-[#ffb4ab]">Revisão manual</small><h3 className="mt-2 text-lg font-semibold">Decisões pendentes</h3><p className="mt-1 text-sm text-[#c9b9b7]">Conflitos e lacunas que precisam de você.</p></div><span className="text-3xl">›</span></Link></div>}
  {tab==='pobj'&&<div className="space-y-5 px-6"><section className="rounded-[32px] bg-[#1d1d1f] p-7 text-center"><small className="font-bold uppercase tracking-wider text-[#b9bbc5]">Desempenho geral · demo</small><div className="mx-auto mt-7 grid h-48 w-48 place-items-center rounded-full bg-[conic-gradient(#a9c3ff_0_85%,#353535_85%)]"><div className="grid h-36 w-36 place-items-center rounded-full bg-[#1d1d1f]"><b className="text-5xl">85%</b></div></div></section><div className="grid grid-cols-2 gap-3">{[['Meta','1000 pts'],['Projeção','920 pts'],['Risco','Médio'],['Prazo','4 dias']].map(x=><article className="rounded-[26px] bg-[#1d1d1f] p-5" key={x[0]}><small className="uppercase text-[#aeb1bd]">{x[0]}</small><b className="mt-4 block text-xl">{x[1]}</b></article>)}</div></div>}
  {tab==='carteira'&&<div className="px-6"><input className="h-14 w-full rounded-[20px] bg-[#1d1d1f] px-5 outline-none" placeholder="Buscar empresa..."/><div className="mt-5 flex gap-2 overflow-auto">{['Atenção','Sem contato','Rating/Sale'].map(x=><button className="shrink-0 rounded-full bg-[#242426] px-4 py-2 text-sm" key={x}>{x}</button>)}</div><div className="mt-6 space-y-3">{clients.map(c=><button onClick={()=>setSheet(c[0])} className="w-full rounded-[28px] bg-[#1d1d1f] p-5 text-left" key={c[0]}><b className="text-lg">{c[0]}</b><p className="mt-1 text-sm text-[#aeb1bd]">{c[1]}</p><p className="mt-5 rounded-[18px] bg-[#28282a] p-4 text-sm">{c[2]}</p></button>)}</div></div>}
  {tab==='chat'&&<div className="flex min-h-[70dvh] flex-col px-6"><div className="flex items-center gap-4 rounded-[28px] bg-[#1d1d1f] p-4"><span className="text-4xl">🤖</span><div><b>Diretor 360</b><p className="text-sm text-[#55eca0]">● Parceiro executivo</p></div></div><div className="mt-5 rounded-[24px] bg-[#1d1d1f] p-5 text-sm leading-6">Bom dia, Rafael. Posso integrar POBJ, carteira e relacionamento para definir o que merece atenção agora.</div><div className="mt-auto flex gap-2 rounded-[24px] bg-[#1d1d1f] p-2"><input value={message} onChange={e=>setMessage(e.target.value)} className="min-w-0 flex-1 bg-transparent px-3 outline-none" placeholder="Converse com o Diretor..."/><button onClick={()=>setMessage('')} className="h-12 w-12 rounded-full bg-[#568dff] font-bold text-[#071d48]">↑</button></div></div>}
  {tab==='mais'&&<div className="space-y-3 px-6">{[['Conta','Saúde, carteira e oportunidades'],['Performance','POBJ, metas e execução'],['Financeiro','Resultado, retorno e cenários'],['Relacionamento','Conversas e compromissos']].map(x=><button onClick={()=>setTab('chat')} className="flex w-full items-center justify-between rounded-[28px] bg-[#1d1d1f] p-5 text-left" key={x[0]}><span><b>{x[0]}</b><small className="mt-1 block text-[#aeb1bd]">{x[1]}</small></span><small className="text-[#55eca0]">APPROVED</small></button>)}</div>}
 </div><Bottom tab={tab} setTab={setTab}/>{sheet&&<div onClick={()=>setSheet(null)} className="fixed inset-0 z-50 bg-black/70"><section onClick={e=>e.stopPropagation()} className="absolute inset-x-0 bottom-0 mx-auto max-w-[520px] rounded-t-[34px] bg-[#1d1d1f] p-7 pb-10"><div className="mx-auto mb-6 h-1.5 w-12 rounded-full bg-[#555]"/><h2 className="text-2xl font-semibold">{sheet}</h2><p className="mt-3 text-[#bec0c9]">Consulte evidências, data-base, impacto e a decisão necessária.</p><button onClick={()=>setSheet(null)} className="mt-7 h-14 w-full rounded-full bg-[#568dff] font-bold text-[#071d48]">Entendi</button></section></div>}</main>
}
function Score(){return <section className="rounded-[32px] bg-gradient-to-br from-[#242427] to-[#171918] p-6"><div className="flex justify-between text-xs font-bold uppercase tracking-wider text-[#c7cad5]"><span>POBJ atual</span><span className="text-[#ffcc3f]">dados demo</span></div><div className="mt-5"><b className="text-5xl">850</b><span className="ml-2 text-lg text-[#c2c6d6]">/ 1000</span></div><div className="mt-7 h-3 rounded-full bg-[#343434]"><div className="h-full w-[85%] rounded-full bg-[#568dff]"/></div><div className="mt-4 flex justify-between text-xs text-[#b9bbc5]"><span>85% atingido</span><span>150 pts para 100%</span></div></section>}
function Bottom({tab,setTab}:{tab:Tab;setTab:(t:Tab)=>void}){return <nav className="fixed bottom-[max(14px,env(safe-area-inset-bottom))] left-1/2 z-40 flex h-[78px] w-[calc(100%-28px)] max-w-[490px] -translate-x-1/2 justify-around rounded-[30px] border border-white/10 bg-[#202020]/95 px-2 backdrop-blur-xl">{([['inicio','⌂','Início'],['pobj','◎','POBJ'],['carteira','▣','Carteira'],['chat','◆','Chat'],['mais','☰','Mais']] as const).map(n=><button onClick={()=>setTab(n[0])} className="flex min-w-14 flex-col items-center justify-center gap-1 text-[10px]" key={n[0]}><span className={'grid h-8 min-w-12 place-items-center rounded-full text-lg '+(tab===n[0]?'bg-[#568dff] text-[#071d48]':'')}>{n[1]}</span>{n[2]}</button>)}</nav>}
